"""Initial schema

Revision ID: 5abc9dddb86b
Revises: 
Create Date: 2026-01-16 19:41:14.679129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abc9dddb86b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Transactions',
    sa.Column('TransactionID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('EntryDate', sa.DateTime(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['dbo.Customers.CustomerID'], ),
    sa.PrimaryKeyConstraint('TransactionID'),
    schema='Ledger'
    )
    op.create_index(op.f('ix_Ledger_Transactions_TransactionID'), 'Transactions', ['TransactionID'], unique=False, schema='Ledger')
    op.alter_column('Customers', 'CustomerName',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.create_index(op.f('ix_dbo_Customers_CustomerID'), 'Customers', ['CustomerID'], unique=False, schema='dbo')
    op.alter_column('users', 'email',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_index(op.f('ix_dbo_Customers_CustomerID'), table_name='Customers', schema='dbo')
    op.alter_column('Customers', 'CustomerName',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_index(op.f('ix_Ledger_Transactions_TransactionID'), table_name='Transactions', schema='Ledger')
    op.drop_table('Transactions', schema='Ledger')
    # ### end Alembic commands ###
