"""Initial Schema with Ledger

Revision ID: c9b140db1923
Revises:
Create Date: 2026-01-17 13:00:25.328302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9b140db1923"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    # 1. CREATE CUSTOMERS FIRST (The Foundation)
    # This must happen before Transactions because Transactions points to it.
    op.create_table(
        "Customers",
        sa.Column("CustomerID", sa.Integer(), nullable=False),
        sa.Column("CustomerName", sa.String(length=100), nullable=True),
        sa.Column("Email", sa.String(length=255), nullable=True),
        sa.Column("PhoneNumber", sa.String(length=20), nullable=True),
        sa.Column("HomeAddress", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("CustomerID"),
    )
    op.create_index(
        op.f("ix_Customers_CustomerID"), "Customers", ["CustomerID"], unique=False
    )
    op.create_index(op.f("ix_Customers_Email"), "Customers", ["Email"], unique=False)

    # 2. CREATE USERS (Independent)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)

    # 3. CREATE TRANSACTIONS (The Child)
    # Now that Customers exists, this will work.

    # === AZURE SQL (LEDGER MODE) ===
    if bind.engine.name == "mssql":
        op.execute("""
            CREATE TABLE [dbo].[Transactions] (
                [TransactionID] INTEGER NOT NULL IDENTITY(1,1),
                [CustomerID] INTEGER NULL,
                [Amount] DECIMAL(18, 2) NULL,
                [EntryDate] DATETIME NULL,
                [Notes] VARCHAR(max) NULL,
                PRIMARY KEY ([TransactionID]),
                FOREIGN KEY([CustomerID]) REFERENCES [dbo].[Customers] ([CustomerID])
            ) 
            WITH (
                SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[TransactionsHistory]),
                LEDGER = ON
            );
        """)
        op.create_index(
            op.f("ix_Transactions_TransactionID"),
            "Transactions",
            ["TransactionID"],
            unique=False,
            schema="dbo",
        )

    # === SQLITE (STANDARD MODE) ===
    else:
        op.create_table(
            "Transactions",
            sa.Column("TransactionID", sa.Integer(), nullable=False),
            sa.Column("CustomerID", sa.Integer(), nullable=True),
            sa.Column("Amount", sa.DECIMAL(precision=18, scale=2), nullable=True),
            sa.Column("EntryDate", sa.DateTime(), nullable=True),
            sa.Column("Notes", sa.String(), nullable=True),
            sa.PrimaryKeyConstraint("TransactionID"),
        )
        op.create_index(
            op.f("ix_Transactions_TransactionID"),
            "Transactions",
            ["TransactionID"],
            unique=False,
        )
        op.create_foreign_key(
            None, "Transactions", "Customers", ["CustomerID"], ["CustomerID"]
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.NVARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
        nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(),
        type_=sa.NVARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
        nullable=False,
    )
    op.drop_index(op.f("ix_Customers_CustomerID"), table_name="Customers")
    op.alter_column(
        "Customers",
        "CustomerName",
        existing_type=sa.NVARCHAR(length=100, collation="SQL_Latin1_General_CP1_CI_AS"),
        nullable=False,
    )
    op.drop_index(op.f("ix_Transactions_TransactionID"), table_name="Transactions")
    op.drop_table("Transactions")
    # ### end Alembic commands ###
